### ISSUE TITLE
VL.Lobe test for REST API 

### ISSUE THREAD

**Issue by quantum-fusion** [sebescudie/VL.Lobe#1]
Hello, I tried installing your VL.Lobe and can not get my REST API running, because there is a connection refused.

See transcript below: 
nuget install VL.Lobe -pre
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'VL.Lobe' to '/Users/hottelet/Desktop/LobeTestProject'.
  GET https://api.nuget.org/v3/registration5-gz-semver2/vl.lobe/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/vl.lobe/index.json 143ms

Attempting to gather dependency information for package 'VL.Lobe.1.0.0-beta01' with respect to project '/Users/hottelet/Desktop/LobeTestProject', targeting 'Any,Version=v0.0'
Gathering dependency information took 9.58 sec
Attempting to resolve dependencies for package 'VL.Lobe.1.0.0-beta01' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'VL.Lobe.1.0.0-beta01'
Resolved actions to install package 'VL.Lobe.1.0.0-beta01'
Retrieving package 'RestSharp 106.11.7' from 'nuget.org'.
Retrieving package 'VL.Lobe 1.0.0-beta01' from 'nuget.org'.
Adding package 'RestSharp.106.11.7' to folder '/Users/hottelet/Desktop/LobeTestProject'
Added package 'RestSharp.106.11.7' to folder '/Users/hottelet/Desktop/LobeTestProject'
Successfully installed 'RestSharp 106.11.7' to /Users/hottelet/Desktop/LobeTestProject
Adding package 'VL.Lobe.1.0.0-beta01' to folder '/Users/hottelet/Desktop/LobeTestProject'
Added package 'VL.Lobe.1.0.0-beta01' to folder '/Users/hottelet/Desktop/LobeTestProject'
Successfully installed 'VL.Lobe 1.0.0-beta01' to /Users/hottelet/Desktop/LobeTestProject
Executing nuget actions took 203.03 ms
MacBook-Pro:~/Desktop/LobeTestProject quantum-fusion$ ls
RestSharp.106.11.7				car2.png					truck1.png
Screen Shot 2021-02-12 at 6.42.02 AM.png	car3.png					truck2.png
Screen Shot 2021-02-12 at 9.02.01 AM.png	car4.png					truck3.png
Screen Shot 2021-02-12 at 9.34.23 AM.png	car5.png					truck4.png
VL.Lobe.1.0.0-beta01				car6.png					truck5.png
Vehicles CoreML					test.sh						truck6.png
car.jpg						truck.jpg
car1.png					truck.sh
MacBook-Pro:~/Desktop/LobeTestProject quantum-fusion$ ./test.sh
curl: (7) Failed to connect to localhost port 38100: Connection refused
MacBook-Pro:~/Desktop/LobeTestProject quantum-fusion$ more test.sh

curl --request POST --url http://localhost:38100/predict/1b8ce0b4-fde1-40ec-b2e6-b284f4489438 --data '{"inputs":{"Image":"'$(base64 ./car.jpg)'"}}'

**Comment by sebescudie** [comment]
Hey there,

I just ran the provided help patch with vvvv gamma 2021.3.1 with the latest version of Lobe installed and had no issue. 

Could you describe what you're doing?

**Comment by quantum-fusion** [comment]
@sebescudie I looked at the output of the directory created by VL.Lobe.

-rwxr--r--  1 me  staff  45335 Nov  2 14:25 VL.Lobe.vl
drwxr-xr-x  3 me  staff     96 Mar  1 09:13 help
-rwxr--r--  1 me  staff  30362 Mar  1 09:13 VL.Lobe.1.0.0-beta01.nupkg
MacBook-Pro:~/Desktop/LobeTestProject/VL.Lobe.1.0.0-beta01 quantum-fusion$ 

Question: What is the command line command to get the REST server running with VL.Lobe ?

**Comment by sebescudie** [comment]
There's no command line to run, you just have to use this plugin in vvvv gamma. Just have a look at the help patch, everything's in there.

Once you have trained your model in Lobe, you must go the the export section and select _Local API_. At this point, Lobe exposes a server you can send queries to. This plugin just wraps the REST call and handles image conversion to base 64 for you. You just have to paste the URL that Lobe gives you in the patch.

**Comment by quantum-fusion** [comment]
@sebescudie I am using this curl command provided by the Lobe team from Microsoft.

curl --request POST --url http://localhost:38100/predict/1b8ce0b4-fde1-40ec-b2e6-b284f4489438 --data '{"inputs":{"Image":"'$(base64 ./car.jpg)'"}}'

Result: 
curl: (7) Failed to connect to localhost port 38100: Connection refused

I don't currently have Lobe running, but am in the directory for the saved model.  The model was not exported, because it is the REST API only.

What is missing?  The plugin doesn't seem to work in this case.  Is there a command?

**Comment by sebescudie** [comment]
Not sure why you're referring to curl here. As mentioned, this plugin is meant to be used with [vvvv gamma](https://thegraybook.vvvv.org/).

Also, if your goal is to use the REST API, you have to have Lobe running since the Lobe app takes care of creating the server you'll send commands to.
